const app=document.getElementById('app'),statusEl=document.getElementById('status'),sessionScoreEl=document.getElementById('sessionScore');
let score=0,total=0,currentModule=null,currentIndex=0,content=null,sessionStarted=Date.now();
let patient=JSON.parse(localStorage.getItem('patient')||'null')||{name:'',age:'',notes:''};
let moduleStats=JSON.parse(localStorage.getItem('moduleStats')||'{}');
const modules=[
{id:'word',e:'🧠',t:'Sözcük Bulma',d:'Semantik özellikler, ipucu basamakları ve hedef sözcük erişimi.',c:'#5b5fef',s:'#eeefff'},
{id:'category',e:'🗂️',t:'Kategori',d:'Kategori akıcılığı ve sözcük üretimi.',c:'#22a68a',s:'#e9fbf5'},
{id:'picture',e:'🖼️',t:'Resim Adlandırma',d:'Görsel adlandırma + 3 basamaklı cueing.',c:'#ec4899',s:'#fff0f7'},
{id:'action',e:'🏃',t:'Eylem Adlandırma',d:'Fiil erişimi ve özne–fiil–nesne ağı.',c:'#ff8a4c',s:'#fff2e9'},
{id:'sentence',e:'🗣️',t:'Cümle Kurma',d:'Basit cümleden yapılandırılmış üretime.',c:'#8b5cf6',s:'#f2edff'},
{id:'auditory',e:'👂',t:'İşitsel Anlama',d:'1, 2 ve 3 aşamalı komutlar.',c:'#2f80ed',s:'#eaf3ff'},
{id:'reading',e:'📖',t:'Okuduğunu Anlama',d:'Cümle ve kısa metinlerle soru-cevap.',c:'#f1a72b',s:'#fff8e7'},
{id:'story',e:'🎬',t:'Resimli Anlatım',d:'Olay örgüsü, zaman bağlaçları ve anlatım.',c:'#e95b76',s:'#fff0f3'}
];
const fallback={version:'0',modules:{word:[],category:[],picture:[],action:[],sentence:[],auditory:[],reading:[],story:[]}};
async function loadContent(force=false){statusEl.textContent='İçerik kontrol ediliyor…';const remote=localStorage.getItem('contentUrl')||'./content.json';try{const r=await fetch(remote+(remote.includes('?')?'&':'?')+'v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);content=await r.json();localStorage.setItem('contentCache',JSON.stringify(content));statusEl.textContent=`İçerik ${content.version||''} hazır`;if(force)toast('Yeni içerik paketi yüklendi.')}catch(e){content=JSON.parse(localStorage.getItem('contentCache')||'null')||fallback;statusEl.textContent='Çevrimdışı içerik kullanılıyor';if(force)toast('Güncelleme alınamadı; kayıtlı içerik kullanılıyor.')}}
function data(id){return content?.modules?.[id]||[]}
function pct(x){return x.t?Math.round(x.c/x.t*100):0}
function home(){currentModule=null;const totalItems=modules.reduce((n,m)=>n+data(m.id).length,0);app.innerHTML=`<section class="hero"><h1>Afazi Terapi ✨</h1><p>Terapiyi daha renkli, daha akıcı ve daha zengin içerikle yürütmek için tasarlanmış DKT çalışma alanı. İçerik paketi internetten yenilenebilir.</p><div class="quick"><button class="btn" id="patientBtn">👤 Danışan</button><button class="btn" id="dashboardBtn">📊 Seans paneli</button><button class="btn" id="contentBtn">☁️ İçerikleri güncelle</button><button class="btn ghost" id="shuffleBtn">🎲 Karışık egzersiz</button></div><div class="mini-note" style="color:#fff;opacity:.85;margin-top:12px">Bu pakette toplam <b>${totalItems}</b> egzersiz bulunuyor.</div></section><div class="module-grid">${modules.map(m=>`<article class="module" style="--accent:${m.c};--soft:${m.s}" data-id="${m.id}"><span class="count">${data(m.id).length} örnek</span><div class="module-icon">${m.e}</div><h3>${m.t}</h3><p>${m.d}</p></article>`).join('')}</div><div class="section-title"><h2>Bu seans</h2><span class="tag">${patient.name?escape(patient.name):'Danışan seçilmedi'}</span></div><section class="card"><div class="stats"><div class="stat"><span>Doğru</span><b>${score}</b></div><div class="stat"><span>Toplam</span><b>${total}</b></div><div class="stat"><span>Başarı</span><b>${total?Math.round(score/total*100):0}%</b></div><div class="stat"><span>İçerik</span><b>${totalItems}</b></div></div><div class="toolbar"><button class="btn alt" id="reset">↺ Seansı sıfırla</button><button class="btn good" id="saveSession">💾 Seansı kaydet</button><button class="btn ghost" id="export">📤 JSON dışa aktar</button></div></section><div class="section-title"><h2>Modül performansı</h2></div><section class="card"><div class="list">${modules.map(m=>{const x=moduleStats[m.id]||{c:0,t:0};return `<div class="list-item"><b>${m.e} ${m.t}</b><span class="pill" style="float:right">${pct(x)}%</span><small class="help">${x.c}/${x.t} doğru</small></div>`}).join('')}</div></section>`;bindHome()}
function bindHome(){document.querySelectorAll('.module').forEach(x=>x.onclick=()=>openModule(x.dataset.id));document.getElementById('reset').onclick=()=>{score=0;total=0;moduleStats={};localStorage.setItem('moduleStats','{}');sessionStarted=Date.now();updateScore();home()};document.getElementById('patientBtn').onclick=patientScreen;document.getElementById('dashboardBtn').onclick=dashboard;document.getElementById('contentBtn').onclick=contentManager;document.getElementById('saveSession').onclick=saveSession;document.getElementById('export').onclick=exportSession;document.getElementById('shuffleBtn').onclick=randomExercise}
function openModule(id){currentModule=id;currentIndex=0;({word:renderWord,picture:renderPicture,category:renderCategory,action:renderAction,sentence:renderSentence,auditory:renderAuditory,reading:renderReading,story:renderStory})[id]?.()}
function shell(title,body){const n=Math.max(1,data(currentModule).length);const progress=Math.min(100,((currentIndex%n)+1)/n*100);return `<div class="exercise"><button class="btn alt" id="back">← Menü</button><div class="progress"><i style="width:${progress}%"></i></div><div class="prompt">${title}</div>${body}</div>`}
function bindBack(){document.getElementById('back').onclick=home}
function mark(ok){total++;if(ok)score++;const st=moduleStats[currentModule]||{c:0,t:0};st.t++;if(ok)st.c++;moduleStats[currentModule]=st;localStorage.setItem('moduleStats',JSON.stringify(moduleStats));updateScore();return ok}
function updateScore(){sessionScoreEl.textContent=`${score}/${total}`}
function next(fn){currentIndex++;fn()}
function renderWord(){const r=data('word')[currentIndex%data('word').length];if(!r)return emptyModule();app.innerHTML=shell('Bu sözcüğü bul.',`<div class="imagebox"><img id="pic" src="${r.image}" alt="${escape(r.answer)}"></div><div class="two"><div class="card"><span class="tag">Kategori</span><h3>${escape(r.category)}</h3><div class="chips">${r.features.map(x=>`<button class="chip cue">${escape(x)}</button>`).join('')}</div></div><div class="card"><span class="tag">Hedef</span><h2>${escape(r.answer)}</h2><div class="feedback" id="feedback">Önce bağımsız yanıtı bekleyin.</div></div></div><div class="toolbar"><button class="btn" id="listen">🔊 Hedefi dinle</button><button class="btn good" id="correct">✓ Başarılı</button><button class="btn bad" id="wrong">✗ Başarısız</button><button class="btn orange" id="next">Sonraki →</button></div>`);bindBack();document.getElementById('correct').onclick=()=>{mark(true);feedback.textContent='Başarılı kaydedildi.'};document.getElementById('wrong').onclick=()=>{mark(false);feedback.textContent='Cueing basamağı kullanılabilir.'};document.getElementById('next').onclick=()=>next(renderWord);document.getElementById('listen').onclick=()=>speak(r.answer);document.querySelectorAll('.cue').forEach(b=>b.onclick=()=>speak(b.textContent))}
function renderPicture(){const r=data('picture')[currentIndex%data('picture').length];if(!r)return emptyModule();app.innerHTML=shell('Resme bak: Bu nedir?',`<div class="imagebox"><img src="${r.image}" alt="${escape(r.answer)}"></div><div class="hint-grid"><div class="hint"><b>İpucu 1</b>${escape(r.cue1)}</div><div class="hint"><b>İpucu 2</b>${escape(r.cue2)}</div><div class="hint"><b>İpucu 3</b>${escape(r.cue3)}</div></div><div class="feedback" id="feedback">Yanıtı bekleyin; gerekirse ipuçlarını sırayla açın.</div><div class="toolbar"><button class="btn" onclick="showCue('${escape(r.cue1)}')">İpucu 1</button><button class="btn" onclick="showCue('${escape(r.cue2)}')">İpucu 2</button><button class="btn" onclick="showCue('${escape(r.cue3)}')">İpucu 3</button><button class="btn good" id="yes">✓ Doğru</button><button class="btn bad" id="no">✗ Yanlış</button><button class="btn orange" id="next">Sonraki</button></div>`);bindBack();document.getElementById('yes').onclick=()=>mark(true);document.getElementById('no').onclick=()=>mark(false);document.getElementById('next').onclick=()=>next(renderPicture)}
function showCue(x){feedback.textContent=x;speak(x)}
function renderCategory(){const r=data('category')[currentIndex%data('category').length];if(!r)return emptyModule();app.innerHTML=shell(`${escape(r.title)} — ${r.targetCount} sözcük hedefle`, `<div class="card"><p>${escape(r.cue)}</p><div class="chips">${r.items.map(x=>`<span class="chip">${escape(x)}</span>`).join('')}</div><div class="field"><label>Danışanın ürettiği sözcükler</label><textarea id="catAnswer" rows="5" placeholder="Sözcükleri virgülle ayırabilirsiniz"></textarea></div><div class="feedback" id="feedback"></div></div><div class="toolbar"><button class="btn good" id="goal">✓ Hedefe ulaştı</button><button class="btn bad" id="miss">✗ Ulaşamadı</button><button class="btn orange" id="next">Sonraki</button></div>`);bindBack();document.getElementById('goal').onclick=()=>{mark(true);feedback.textContent='Hedef kaydedildi.'};document.getElementById('miss').onclick=()=>{mark(false);feedback.textContent='Hedefe ulaşılamadı.'};document.getElementById('next').onclick=()=>next(renderCategory)}
function renderAction(){const r=data('action')[currentIndex%data('action').length];if(!r)return emptyModule();app.innerHTML=shell('Eylemi adlandır ve ağ kur.',`<div class="imagebox"><div style="font-size:90px">🏃‍♂️</div></div><div class="feature-card"><div class="big">🔗</div><div><b>Kim?</b><br>${escape(r.who)}</div><div><b>Ne yapıyor?</b><br>${escape(r.verb)}</div><div><b>Neyi?</b><br>${escape(r.object)}</div></div><div class="card" style="margin-top:12px"><b>Örnek cümle:</b> ${escape(r.sentence)}<div class="field"><label>Danışanın cümlesi</label><textarea id="answer" rows="3" placeholder="Cümleyi yazabilirsiniz"></textarea></div></div><div class="toolbar"><button class="btn" onclick="speak('${escape(r.answer)}')">🔊 Eylemi dinle</button><button class="btn good" id="yes">✓ Başarılı</button><button class="btn bad" id="no">✗ Başarısız</button><button class="btn orange" id="next">Sonraki</button></div>`);bindBack();document.getElementById('yes').onclick=()=>mark(true);document.getElementById('no').onclick=()=>mark(false);document.getElementById('next').onclick=()=>next(renderAction)}
function renderSentence(){const r=data('sentence')[currentIndex%data('sentence').length];if(!r)return emptyModule();app.innerHTML=shell('Cümleyi kur.',`<div class="card"><div class="hint-grid"><div class="hint"><b>Kim?</b>${escape(r.who)}</div><div class="hint"><b>Ne yapıyor?</b>${escape(r.verb)}</div><div class="hint"><b>Neyi?</b>${escape(r.object)}</div></div><div class="field"><label>Danışanın cümlesi</label><textarea id="answer" rows="3" placeholder="Cümleyi yazın"></textarea></div><div class="feedback" id="feedback">Hedef: ${escape(r.sentence)}</div></div><div class="toolbar"><button class="btn" id="listen">🔊 Hedefi dinle</button><button class="btn good" id="yes">✓ Başarılı</button><button class="btn bad" id="no">✗ Başarısız</button><button class="btn orange" id="next">Sonraki</button></div>`);bindBack();document.getElementById('listen').onclick=()=>speak(r.sentence);document.getElementById('yes').onclick=()=>mark(true);document.getElementById('no').onclick=()=>mark(false);document.getElementById('next').onclick=()=>next(renderSentence)}
function renderAuditory(){const r=data('auditory')[currentIndex%data('auditory').length];if(!r)return emptyModule();app.innerHTML=shell(`Komutu dinle — Düzey ${r.level}`,`<div class="card" style="text-align:center"><div style="font-size:70px">👂</div><h2>Komutu dinleyin</h2><p class="mini-note">Danışana göstermeden önce seslendirin.</p><div class="toolbar center"><button class="btn" id="listen">🔊 Komutu seslendir</button><button class="btn ghost" id="reveal">Komutu göster</button></div><div class="feedback" id="feedback"></div></div><div class="toolbar center"><button class="btn good" id="yes">✓ Başarılı</button><button class="btn bad" id="no">✗ Başarısız</button><button class="btn orange" id="next">Sonraki</button></div>`);bindBack();document.getElementById('listen').onclick=()=>speak(r.command);document.getElementById('reveal').onclick=()=>feedback.textContent=r.command;document.getElementById('yes').onclick=()=>mark(true);document.getElementById('no').onclick=()=>mark(false);document.getElementById('next').onclick=()=>next(renderAuditory)}
function renderReading(){const r=data('reading')[currentIndex%data('reading').length];if(!r)return emptyModule();app.innerHTML=shell('Metni oku ve soruyu yanıtla.',`<div class="card"><div style="font-size:18px;line-height:1.7">${escape(r.text)}</div><hr><b>${escape(r.question)}</b><div class="field"><textarea id="answer" rows="3" placeholder="Yanıt"></textarea></div><div class="feedback" id="feedback">Hedef yanıt: ${escape(r.answer)}</div></div><div class="toolbar"><button class="btn" onclick="speak('${escape(r.text)}')">🔊 Metni dinle</button><button class="btn good" id="yes">✓ Doğru</button><button class="btn bad" id="no">✗ Yanlış</button><button class="btn orange" id="next">Sonraki</button></div>`);bindBack();document.getElementById('yes').onclick=()=>mark(true);document.getElementById('no').onclick=()=>mark(false);document.getElementById('next').onclick=()=>next(renderReading)}
function renderStory(){const r=data('story')[currentIndex%data('story').length];if(!r)return emptyModule();app.innerHTML=shell(escape(r.title),`<div class="imagebox"><img src="${r.image}" alt="${escape(r.title)}"></div><div class="card"><p>${escape(r.prompt)}</p><div class="field"><label>Terapist notu</label><textarea id="note" rows="6" placeholder="Sözcük bulma, cümle yapısı, anlatım sırası, bağlaçlar…"></textarea></div><div class="toolbar"><button class="btn" id="listen">🔊 Görevi seslendir</button><button class="btn good" id="yes">✓ Hedef tamam</button><button class="btn bad" id="no">✗ Ek destek gerekli</button><button class="btn orange" id="next">Sonraki</button></div></div>`);bindBack();document.getElementById('listen').onclick=()=>speak(r.prompt);document.getElementById('yes').onclick=()=>mark(true);document.getElementById('no').onclick=()=>mark(false);document.getElementById('next').onclick=()=>{saveStoryNote(r.id);next(renderStory)}}
function saveStoryNote(id){const notes=JSON.parse(localStorage.getItem('storyNotes')||'{}');const el=document.getElementById('note');if(el)notes[id]=el.value;localStorage.setItem('storyNotes',JSON.stringify(notes))}
function randomExercise(){const available=modules.filter(m=>data(m.id).length);const m=available[Math.floor(Math.random()*available.length)];openModule(m.id);toast(`${m.t} seçildi`)}
function patientScreen(){app.innerHTML=`<div class="exercise"><button class="btn alt" id="back">← Menü</button><div class="prompt">Danışan profili</div><div class="card"><div class="two"><div class="field"><label>Ad</label><input id="pname" value="${escape(patient.name)}"></div><div class="field"><label>Yaş</label><input id="page" value="${escape(patient.age)}"></div></div><div class="field"><label>Genel not</label><textarea id="pnotes" rows="5">${escape(patient.notes)}</textarea></div><button class="btn good" id="save">💾 Kaydet</button></div></div>`;bindBack();document.getElementById('save').onclick=()=>{patient={name:pname.value,age:page.value,notes:pnotes.value};localStorage.setItem('patient',JSON.stringify(patient));toast('Danışan kaydedildi');home()}}
function dashboard(){const history=JSON.parse(localStorage.getItem('sessions')||'[]');app.innerHTML=`<div class="exercise"><button class="btn alt" id="back">← Menü</button><div class="prompt">Seans paneli</div><div class="stats"><div class="stat"><span>Bu seans</span><b>${total}</b></div><div class="stat"><span>Başarı</span><b>${total?Math.round(score/total*100):0}%</b></div><div class="stat"><span>Kayıtlı seans</span><b>${history.length}</b></div><div class="stat"><span>Danışan</span><b>${escape(patient.name||'—')}</b></div></div><div class="section-title"><h2>Modül bazlı performans</h2></div><div class="list">${modules.map(m=>{const x=moduleStats[m.id]||{c:0,t:0};return `<div class="list-item"><b>${m.e} ${m.t}</b><span class="pill" style="float:right">${pct(x)}%</span><small class="help">${x.c}/${x.t} doğru</small></div>`}).join('')}</div><div class="section-title"><h2>Son kayıtlar</h2></div><div class="list">${history.slice(-8).reverse().map(x=>`<div class="list-item"><b>${new Date(x.date).toLocaleString('tr-TR')}</b><small class="help">${escape(x.patient||'')} · ${x.score}/${x.total} · ${x.total?Math.round(x.score/x.total*100):0}%</small></div>`).join('')||'<div class="empty">Henüz kayıt yok.</div>'}</div></div>`;bindBack()}
function saveSession(){const history=JSON.parse(localStorage.getItem('sessions')||'[]');history.push({date:new Date().toISOString(),patient:patient.name,score,total,modules:moduleStats});localStorage.setItem('sessions',JSON.stringify(history.slice(-100)));toast('Seans kaydedildi')}
function exportSession(){download('afazi-terapi-seans.json',JSON.stringify({patient,score,total,moduleStats,date:new Date().toISOString()},null,2),'application/json')}
function contentManager(){const remote=localStorage.getItem('contentUrl')||'./content.json';app.innerHTML=`<div class="exercise"><button class="btn alt" id="back">← Menü</button><div class="prompt">İçerik merkezi ☁️</div><div class="card"><div class="feature-card"><div class="big">🔄</div><div><b>Otomatik yenileme</b><div class="mini-note">GitHub'daki content.json değiştiğinde buradan yeni paketi çekebilirsiniz.</div></div></div><div class="field"><label>Uzak içerik adresi</label><input id="url" value="${escape(remote)}"><small class="help">Varsayılan: ./content.json</small></div><div class="toolbar"><button class="btn good" id="refresh">↻ Şimdi güncelle</button><button class="btn" id="saveUrl">💾 Adresi kaydet</button></div><hr><h3>İçerik dosyası</h3><input type="file" id="file" accept="application/json"><div class="toolbar"><button class="btn ghost" id="downloadContent">📤 Mevcut içeriği indir</button></div><small class="help">Yeni örnekler eklemek için content.json dosyasını düzenleyip GitHub'a gönderin. Site yeni sürümü otomatik yayınlar.</small><hr><h3>AI bağlantısı</h3><input id="ai" value="${escape(localStorage.getItem('aiEndpoint')||'')}" placeholder="https://sunucunuz.example/api/generate"><small class="help">API anahtarını tarayıcıya/GitHub'a koymayın. Güvenli sunucu üzerinden bağlayın.</small><button class="btn" id="saveAi" style="margin-top:10px">AI adresini kaydet</button></div></div>`;bindBack();document.getElementById('saveUrl').onclick=()=>{localStorage.setItem('contentUrl',url.value.trim()||'./content.json');toast('İçerik adresi kaydedildi')};document.getElementById('refresh').onclick=async()=>{localStorage.setItem('contentUrl',url.value.trim()||'./content.json');await loadContent(true);home()};document.getElementById('saveAi').onclick=()=>{localStorage.setItem('aiEndpoint',ai.value.trim());toast('AI endpoint kaydedildi')};document.getElementById('file').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{content=JSON.parse(rd.result);localStorage.setItem('contentCache',JSON.stringify(content));toast('Yeni içerik paketi yüklendi');home()}catch(err){toast('JSON dosyası geçersiz')}};rd.readAsText(f)};document.getElementById('downloadContent').onclick=()=>download('content.json',JSON.stringify(content,null,2),'application/json')}
function aiSettings(){contentManager()}
function speak(text){if('speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='tr-TR';speechSynthesis.speak(u)}}
function emptyModule(){app.innerHTML=`<div class="exercise"><button class="btn alt" id="back">← Menü</button><div class="prompt">İçerik yok</div><div class="empty">Bu modülde henüz içerik bulunmuyor.</div></div>`;bindBack()}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
function escape(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.getElementById('homeBtn').onclick=home;document.getElementById('settingsBtn').onclick=contentManager;(async()=>{await loadContent();home();updateScore()})();